### ISSUE TITLE
consider forbidding object-shorthand 

### ISSUE THREAD

**Issue by blizzz** [nextcloud-libraries/eslint-config#835]
…t least for properties. Shorthands can be highly confusing, as they mix key with data, which also can be error-prone on refactorings. Eg.:

```js
				await this.$store.dispatch('insertNewRow', {
					viewId: this.isView ? this.elementId : null,
					tableId: !this.isView ? this.elementId : null,
					data,
				})
```

for the casual js reader or writer, it is not very clear that `data` is both key and value here, it just appears as if it is just appended… but to an object. Sure it does work and such, but is terrible for readability.

**Comment by Antreesy** [comment]
IMO that is greatly reducing the boilerplate if applicable. I even renamed some of them specifically to shorthand, so that I'm sure that passed from component `messageId` will be named the same in store and in API middleware.

Maybe `data` is not meaningful enough, but then it shouldn't be named like this and not to be shorthanded in the first place

**Comment by ShGKme** [comment]
Object shorthand is quite an old (2015) and widely used JS feature. There is no "appending" in JS objects. It works fine with automatic refactoring in IDEs. And makes objects description short and simple in many cases.

I don't know in which case it may lead to an error (maybe except during find-and-replace refactoring, which is always dangerous).

In addition, Vue now has a similar shorthand for attributes.
```html
<UserCard :email="email" :name="name" :avatar="avatar" />
<!-- same as -->
<UserCard :email :name :avatar />
```

**Comment by max-nextcloud** [comment]
I like it as it encourages refactorings like this:

```js
const viewId = this.isView ? this.elementId : null
const tableId = !this.isView ? this.elementId : null
await this.$store.dispatch('insertNewRow', { viewId, tableId, data })
```

This separates the 'computation' of the `viewId` and `tableId` from the function call - which I think improves readability. I probably would not do it though if then it would require me to write:

```js
const viewId = this.isView ? this.elementId : null
const tableId = !this.isView ? this.elementId : null
await this.$store.dispatch('insertNewRow', { viewId: viewId, tableId: tableId, data: data })
```

**Comment by blizzz** [comment]
> I don't know in which case it may lead to an error (maybe except during find-and-replace refactoring, which is always dangerous).

You change a variable and suddenly you borked the API parameter name.

**Comment by susnux** [comment]
> You change a variable and suddenly you borked the API parameter name you meant to use.

Yes but only if you do it with find-and-replace, and this is always bad if you do not check what you are doing.
Automatic refactoring provided by IDEs correctly handle this case and will add a key to keep the API behavior.

---

I have to say I strongly disagree with this idea, this is something *very common* in the JS / TS ecosystem.
Max nicely pointed out one of the huge benefits for clean code, in general I think it makes code **much** better readable.

Because you now separate the variable computation from a method call / object instantiation, I would like to extend Max example to show what I see more often than I wish I would do:

```js
await this.$store.dispatch(
    'insertNewRow',
    {
        viewId: this.isView ? this.elementId : null,
        tableId: !this.isView ? this.elementId : null,
        data: this.fetchData(),
    },
)
```

When reading this, this is just a huge block of code, that is very nested. You have a function call and with three parameters that are conditionals or functions calls. It is much harder to understand, test and refactor.

Even in the second example of Max which seems to be clean, I think it just is duplicated code which does not bring any benefits and for me even slows down reading because it makes me notice key and value as separate things instead of "ok we pass `viewId`".
